import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request'
import FoodCard from '../components/FoodCard'
import { useState } from 'react'


// fetching data from Graph CMS API
const graphcms = new GraphQLClient(
  'https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/cl9bp0cvy3x2t01ta1sea37y9/master'
)

// querying the data from API
const QUERY = gql`
  {
    foods (first: 500) {
      title
      slug
      coverPhoto {
        url
      }
      price
      category
    }
  }
`

// fetch request
export async function getStaticProps() {
  const { foods } = await graphcms.request(QUERY)
  return {
    props: {
      // always return data
      foods,
    },
    revalidate: 10, // if new content will add, generates every each 10sec
  }
}

export default function Home({ foods }) {

  const categories = [...new Set(foods.map((item)=> item.category))]
  const [filter,setFilter] = useState('')
  const filterByCategory = category => {
    return category.filter((item) => item.category.includes(filter))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Fine Dining</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className={styles.heading}>Fine Dining</h1>

      <main className={styles.main}>
      <select onChange={(e)=> setFilter(e.target.value)} aria-label="Filter Menu by Category" className={styles.categories}>
      <option value="">all</option>
        {categories.map((item)=>(
          <option value={item}>{item}</option>
        ))}
      </select>
        {filterByCategory(foods).map((food) => (
          <FoodCard
            title={food.title}
            slug={food.slug}
            coverPhoto={food.coverPhoto}
            price={food.price}
            key={food.id}
          />
        ))}
      </main>
    </div>
  )
}
